// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package migrations

type Url struct {
	ID         int64
	UserID     int64
	OrginalUrl string
	ShortUrl   string
}

type User struct {
	ID       int64
	Name     string
	Password string
}
