// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package migrations

import (
	"context"
)

const createUrl = `-- name: CreateUrl :one
INSERT INTO urls (user_id, orginal_url, short_url)
VALUES ($1, $2, $3)
RETURNING id, user_id, orginal_url, short_url
`

type CreateUrlParams struct {
	UserID     int64
	OrginalUrl string
	ShortUrl   string
}

func (q *Queries) CreateUrl(ctx context.Context, arg CreateUrlParams) (Url, error) {
	row := q.db.QueryRow(ctx, createUrl, arg.UserID, arg.OrginalUrl, arg.ShortUrl)
	var i Url
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.OrginalUrl,
		&i.ShortUrl,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (name, password)
VALUES ($1, $2)
RETURNING id, name, password
`

type CreateUserParams struct {
	Name     string
	Password string
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser, arg.Name, arg.Password)
	var i User
	err := row.Scan(&i.ID, &i.Name, &i.Password)
	return i, err
}

const getUser = `-- name: GetUser :one
SELECT id, name, password FROM users
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetUser(ctx context.Context, id int64) (User, error) {
	row := q.db.QueryRow(ctx, getUser, id)
	var i User
	err := row.Scan(&i.ID, &i.Name, &i.Password)
	return i, err
}

const getUserByName = `-- name: GetUserByName :one
SELECT id, name, password FROM users
WHERE name = $1 LIMIT 1
`

func (q *Queries) GetUserByName(ctx context.Context, name string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByName, name)
	var i User
	err := row.Scan(&i.ID, &i.Name, &i.Password)
	return i, err
}

const getUserURLs = `-- name: GetUserURLs :many
SELECT id, user_id, orginal_url, short_url FROM urls
WHERE user_id = $1
`

func (q *Queries) GetUserURLs(ctx context.Context, userID int64) ([]Url, error) {
	rows, err := q.db.Query(ctx, getUserURLs, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Url
	for rows.Next() {
		var i Url
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.OrginalUrl,
			&i.ShortUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
